{"ret":1,"mes":"Load data successfully!","my_bet_data":[{"game_id":"1055961891","date":"13:42:13","user_id":"251410","user_name":"wbhaao","game":"
<span title=\"verify\" onclick=\"show_bet_info(1055961891)\">
    <i class=\"fas fa-bomb\">
        <\/i>
            Mines
            <\/span>
                ","nonce":"987","client_seed":"1ada5563141d4855","server_seed":"88a05ace2eec2347d94f4d008a67ad0f26adf5a78a2861b26ff4c0aeb49a6838","bet_amount":"0.00010000","payout":"
                <span style=\"color: #03a9f4\">
                    0.00\u00d7
                    <\/span>
                        ","profit":"
                        <span style=\"color: #ff5722\">
                            -0.00010000
                            <\/span>
                                "},{"game_id":"1055961187","date":"13:00:06","user_id":"251410","user_name":"wbhaao","game":"
                                <span title=\"verify\" onclick=\"show_bet_info(1055961187)\">
                                    <i class=\"fas fa-bomb\">
                                        <\/i>
                                            Mines
                                            <\/span>
                                                ","nonce":"985","client_seed":"1ada5563141d4855","server_seed":"a543d9c0f843bafc412ab79945afa9a5dd6376552fe548c8fca9f118c551008a","bet_amount":"0.00010000","payout":"
                                                <span style=\"color: #03a9f4\">
                                                    2.51\u00d7
                                                    <\/span>
                                                        ","profit":"
                                                        <span style=\"color: #38cb74\">
                                                            0.00015099
                                                            <\/span>
                                                                "},{"game_id":"1055960612","date":"12:59:49","user_id":"251410","user_name":"wbhaao","game":"
                                                                <span title=\"verify\" onclick=\"show_bet_info(1055960612)\">
                                                                    <i class=\"fas fa-bomb\">
                                                                        <\/i>
                                                                            Mines
                                                                            <\/span>
                                                                                ","nonce":"983","client_seed":"1ada5563141d4855","server_seed":"1a453831808e0cb01221507d485b541cd261ed01ced69fc26246df024500e64b","bet_amount":"0.00010000","payout":"
                                                                                <span style=\"color: #03a9f4\">
                                                                                    1.69\u00d7
                                                                                    <\/span>
                                                                                        ","profit":"
                                                                                        <span style=\"color: #38cb74\">
                                                                                            0.00006900
                                                                                            <\/span>
                                                                                                "},{"game_id":"1055960151","date":"12:59:27","user_id":"251410","user_name":"wbhaao","game":"
                                                                                                <span title=\"verify\" style=\"cursor: pointer\" onclick=\"show_bet_info(1055960151)\">
                                                                                                    <i class=\"fas fa-lemon\">
                                                                                                        <\/i>
                                                                                                            Slots
                                                                                                            <\/span>
                                                                                                                ","nonce":"982","client_seed":"1ada5563141d4855","server_seed":"210373b5c3695b58736cdf77900227362ec050192651bb5c94749ad3469bee01","bet_amount":"0.00010000","payout":"
                                                                                                                <span style=\"color: #03a9f4\">
                                                                                                                    1.00\u00d7
                                                                                                                    <\/span>
                                                                                                                        ","profit":"
                                                                                                                        <span style=\"color: #ff5722\">
                                                                                                                            -0.00020000
                                                                                                                            <\/span>
                                                                                                                                "},{"game_id":"1055960106","date":"12:59:26","user_id":"251410","user_name":"wbhaao","game":"
                                                                                                                                <span title=\"verify\" style=\"cursor: pointer\" onclick=\"show_bet_info(1055960106)\">
                                                                                                                                    <i class=\"fas fa-lemon\">
                                                                                                                                        <\/i>
                                                                                                                                            Slots
                                                                                                                                            <\/span>
                                                                                                                                                ","nonce":"981","client_seed":"1ada5563141d4855","server_seed":"063b1a74755d3b818bb8747f146408ae727e51121f76246cf37c92e57bd3a8a6","bet_amount":"0.00010000","payout":"
                                                                                                                                                <span style=\"color: #03a9f4\">
                                                                                                                                                    0.00\u00d7
                                                                                                                                                    <\/span>
                                                                                                                                                        ","profit":"
                                                                                                                                                        <span style=\"color: #ff5722\">
                                                                                                                                                            -0.00030000
                                                                                                                                                            <\/span>
                                                                                                                                                                "},{"game_id":"1055960058","date":"12:59:25","user_id":"251410","user_name":"wbhaao","game":"
                                                                                                                                                                <span title=\"verify\" style=\"cursor: pointer\" onclick=\"show_bet_info(1055960058)\">
                                                                                                                                                                    <i class=\"fas fa-lemon\">
                                                                                                                                                                        <\/i>
                                                                                                                                                                            Slots
                                                                                                                                                                            <\/span>
                                                                                                                                                                                ","nonce":"980","client_seed":"1ada5563141d4855","server_seed":"7723e9d57acabc964671796c7b66f0f79425cf9a37f1726fab63edb6a6ad7246","bet_amount":"0.00010000","payout":"
                                                                                                                                                                                <span style=\"color: #03a9f4\">
                                                                                                                                                                                    1.00\u00d7
                                                                                                                                                                                    <\/span>
                                                                                                                                                                                        ","profit":"
                                                                                                                                                                                        <span style=\"color: #ff5722\">
                                                                                                                                                                                            -0.00020000
                                                                                                                                                                                            <\/span>
                                                                                                                                                                                                "},{"game_id":"1055960012","date":"12:59:24","user_id":"251410","user_name":"wbhaao","game":"
                                                                                                                                                                                                <span title=\"verify\" style=\"cursor: pointer\" onclick=\"show_bet_info(1055960012)\">
                                                                                                                                                                                                    <i class=\"fas fa-lemon\">
                                                                                                                                                                                                        <\/i>
                                                                                                                                                                                                            Slots
                                                                                                                                                                                                            <\/span>
                                                                                                                                                                                                                ","nonce":"979","client_seed":"1ada5563141d4855","server_seed":"94c49e8a1a86aa3e595777c3af5b30c0439e560009aac08eb0e81fd1d8c08600","bet_amount":"0.00010000","payout":"
                                                                                                                                                                                                                <span style=\"color: #03a9f4\">
                                                                                                                                                                                                                    0.00\u00d7
                                                                                                                                                                                                                    <\/span>
                                                                                                                                                                                                                        ","profit":"
                                                                                                                                                                                                                        <span style=\"color: #ff5722\">
                                                                                                                                                                                                                            -0.00030000
                                                                                                                                                                                                                            <\/span>
                                                                                                                                                                                                                                "},{"game_id":"1055959967","date":"12:59:23","user_id":"251410","user_name":"wbhaao","game":"
                                                                                                                                                                                                                                <span title=\"verify\" style=\"cursor: pointer\" onclick=\"show_bet_info(1055959967)\">
                                                                                                                                                                                                                                    <i class=\"fas fa-lemon\">
                                                                                                                                                                                                                                        <\/i>
                                                                                                                                                                                                                                            Slots
                                                                                                                                                                                                                                            <\/span>
                                                                                                                                                                                                                                                ","nonce":"978","client_seed":"1ada5563141d4855","server_seed":"5c9dcfa1a39fa4213821b788b26bf6da2e5ba7df4f798dad5c6fea7e9e693c53","bet_amount":"0.00010000","payout":"
                                                                                                                                                                                                                                                <span style=\"color: #03a9f4\">
                                                                                                                                                                                                                                                    1.00\u00d7
                                                                                                                                                                                                                                                    <\/span>
                                                                                                                                                                                                                                                        ","profit":"
                                                                                                                                                                                                                                                        <span style=\"color: #ff5722\">
                                                                                                                                                                                                                                                            -0.00020000
                                                                                                                                                                                                                                                            <\/span>
                                                                                                                                                                                                                                                                "},{"game_id":"1055959917","date":"12:59:21","user_id":"251410","user_name":"wbhaao","game":"
                                                                                                                                                                                                                                                                <span title=\"verify\" style=\"cursor: pointer\" onclick=\"show_bet_info(1055959917)\">
                                                                                                                                                                                                                                                                    <i class=\"fas fa-lemon\">
                                                                                                                                                                                                                                                                        <\/i>
                                                                                                                                                                                                                                                                            Slots
                                                                                                                                                                                                                                                                            <\/span>
                                                                                                                                                                                                                                                                                ","nonce":"977","client_seed":"1ada5563141d4855","server_seed":"a51c52282e6c74374317c71033734c0851d5cc1b89964accb516e1853ff46e1b","bet_amount":"0.00010000","payout":"
                                                                                                                                                                                                                                                                                <span style=\"color: #03a9f4\">
                                                                                                                                                                                                                                                                                    2.00\u00d7
                                                                                                                                                                                                                                                                                    <\/span>
                                                                                                                                                                                                                                                                                        ","profit":"
                                                                                                                                                                                                                                                                                        <span style=\"color: #ff5722\">
                                                                                                                                                                                                                                                                                            -0.00010000
                                                                                                                                                                                                                                                                                            <\/span>
                                                                                                                                                                                                                                                                                                "},{"game_id":"1055959874","date":"12:59:20","user_id":"251410","user_name":"wbhaao","game":"
                                                                                                                                                                                                                                                                                                <span title=\"verify\" style=\"cursor: pointer\" onclick=\"show_bet_info(1055959874)\">
                                                                                                                                                                                                                                                                                                    <i class=\"fas fa-lemon\">
                                                                                                                                                                                                                                                                                                        <\/i>
                                                                                                                                                                                                                                                                                                            Slots
                                                                                                                                                                                                                                                                                                            <\/span>
                                                                                                                                                                                                                                                                                                                ","nonce":"976","client_seed":"1ada5563141d4855","server_seed":"14800f8ef4e45c8ed1e25cca9dfa928e31f4b6d8721d0a80fc8fc6e6aa183ea5","bet_amount":"0.00010000","payout":"
                                                                                                                                                                                                                                                                                                                <span style=\"color: #03a9f4\">
                                                                                                                                                                                                                                                                                                                    2.00\u00d7
                                                                                                                                                                                                                                                                                                                    <\/span>
                                                                                                                                                                                                                                                                                                                        ","profit":"
                                                                                                                                                                                                                                                                                                                        <span style=\"color: #ff5722\">
                                                                                                                                                                                                                                                                                                                            -0.00010000
                                                                                                                                                                                                                                                                                                                            <\/span>
                                                                                                                                                                                                                                                                                                                                "},{"game_id":"1055959827","date":"12:59:19","user_id":"251410","user_name":"wbhaao","game":"
                                                                                                                                                                                                                                                                                                                                <span title=\"verify\" style=\"cursor: pointer\" onclick=\"show_bet_info(1055959827)\">
                                                                                                                                                                                                                                                                                                                                    <i class=\"fas fa-lemon\">
                                                                                                                                                                                                                                                                                                                                        <\/i>
                                                                                                                                                                                                                                                                                                                                            Slots
                                                                                                                                                                                                                                                                                                                                            <\/span>
                                                                                                                                                                                                                                                                                                                                                ","nonce":"975","client_seed":"1ada5563141d4855","server_seed":"fbf81c85c375bdc2acccf0e8933feec6d94c3e54982870ed5fb639d2e641e0cc","bet_amount":"0.00010000","payout":"
                                                                                                                                                                                                                                                                                                                                                <span style=\"color: #03a9f4\">
                                                                                                                                                                                                                                                                                                                                                    3.00\u00d7
                                                                                                                                                                                                                                                                                                                                                    <\/span>
                                                                                                                                                                                                                                                                                                                                                        ","profit":"
                                                                                                                                                                                                                                                                                                                                                        <span>
                                                                                                                                                                                                                                                                                                                                                            0.00000000
                                                                                                                                                                                                                                                                                                                                                            <\/span>
                                                                                                                                                                                                                                                                                                                                                                "},{"game_id":"1055959781","date":"12:59:18","user_id":"251410","user_name":"wbhaao","game":"
                                                                                                                                                                                                                                                                                                                                                                <span title=\"verify\" style=\"cursor: pointer\" onclick=\"show_bet_info(1055959781)\">
                                                                                                                                                                                                                                                                                                                                                                    <i class=\"fas fa-lemon\">
                                                                                                                                                                                                                                                                                                                                                                        <\/i>
                                                                                                                                                                                                                                                                                                                                                                            Slots
                                                                                                                                                                                                                                                                                                                                                                            <\/span>
                                                                                                                                                                                                                                                                                                                                                                                ","nonce":"974","client_seed":"1ada5563141d4855","server_seed":"194967de3499b40cc21ce0b441a9c8fbf5cfe4b49be4b914997c09b3436e16e2","bet_amount":"0.00010000","payout":"
                                                                                                                                                                                                                                                                                                                                                                                <span style=\"color: #03a9f4\">
                                                                                                                                                                                                                                                                                                                                                                                    5.00\u00d7
                                                                                                                                                                                                                                                                                                                                                                                    <\/span>
                                                                                                                                                                                                                                                                                                                                                                                        ","profit":"
                                                                                                                                                                                                                                                                                                                                                                                        <span style=\"color: #38cb74\">
                                                                                                                                                                                                                                                                                                                                                                                            0.00020000
                                                                                                                                                                                                                                                                                                                                                                                            <\/span>
                                                                                                                                                                                                                                                                                                                                                                                                "},{"game_id":"1055959726","date":"12:59:16","user_id":"251410","user_name":"wbhaao","game":"
                                                                                                                                                                                                                                                                                                                                                                                                <span title=\"verify\" style=\"cursor: pointer\" onclick=\"show_bet_info(1055959726)\">
                                                                                                                                                                                                                                                                                                                                                                                                    <i class=\"fas fa-lemon\">
                                                                                                                                                                                                                                                                                                                                                                                                        <\/i>
                                                                                                                                                                                                                                                                                                                                                                                                            Slots
                                                                                                                                                                                                                                                                                                                                                                                                            <\/span>
                                                                                                                                                                                                                                                                                                                                                                                                                ","nonce":"973","client_seed":"1ada5563141d4855","server_seed":"9710c4b6cbbff56f5ad97f9da3d135908e7b62a9c32fcdfd088c180ab0ca9519","bet_amount":"0.00010000","payout":"
                                                                                                                                                                                                                                                                                                                                                                                                                <span style=\"color: #03a9f4\">
                                                                                                                                                                                                                                                                                                                                                                                                                    1.00\u00d7
                                                                                                                                                                                                                                                                                                                                                                                                                    <\/span>
                                                                                                                                                                                                                                                                                                                                                                                                                        ","profit":"
                                                                                                                                                                                                                                                                                                                                                                                                                        <span style=\"color: #ff5722\">
                                                                                                                                                                                                                                                                                                                                                                                                                            -0.00020000
                                                                                                                                                                                                                                                                                                                                                                                                                            <\/span>
                                                                                                                                                                                                                                                                                                                                                                                                                                "},{"game_id":"1055959676","date":"12:59:15","user_id":"251410","user_name":"wbhaao","game":"
                                                                                                                                                                                                                                                                                                                                                                                                                                <span title=\"verify\" style=\"cursor: pointer\" onclick=\"show_bet_info(1055959676)\">
                                                                                                                                                                                                                                                                                                                                                                                                                                    <i class=\"fas fa-lemon\">
                                                                                                                                                                                                                                                                                                                                                                                                                                        <\/i>
                                                                                                                                                                                                                                                                                                                                                                                                                                            Slots
                                                                                                                                                                                                                                                                                                                                                                                                                                            <\/span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                ","nonce":"972","client_seed":"1ada5563141d4855","server_seed":"dd6c6f4dbad81000461e49103eaeba392fc86afe3a61b8ee18ec0d1326785b51","bet_amount":"0.00010000","payout":"
                                                                                                                                                                                                                                                                                                                                                                                                                                                <span style=\"color: #03a9f4\">
                                                                                                                                                                                                                                                                                                                                                                                                                                                    2.00\u00d7
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <\/span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        ","profit":"
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span style=\"color: #ff5722\">
                                                                                                                                                                                                                                                                                                                                                                                                                                                            -0.00010000
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <\/span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                "},{"game_id":"1055959629","date":"12:59:14","user_id":"251410","user_name":"wbhaao","game":"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span title=\"verify\" style=\"cursor: pointer\" onclick=\"show_bet_info(1055959629)\">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <i class=\"fas fa-lemon\">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <\/i>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Slots
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <\/span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ","nonce":"971","client_seed":"1ada5563141d4855","server_seed":"80c3720666fe9081599106a4cdf17c7aa61d582e02825df14e03148a25c741c2","bet_amount":"0.00010000","payout":"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span style=\"color: #03a9f4\">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    0.00\u00d7
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <\/span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ","profit":"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span style=\"color: #ff5722\">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            -0.00030000
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <\/span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "},{"game_id":"1055959575","date":"12:59:13","user_id":"251410","user_name":"wbhaao","game":"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span title=\"verify\" style=\"cursor: pointer\" onclick=\"show_bet_info(1055959575)\">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <i class=\"fas fa-lemon\">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <\/i>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Slots
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <\/span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ","nonce":"970","client_seed":"1ada5563141d4855","server_seed":"833b67faa47e42f7e314178d2af1196bbb0b12c9f5e19232b1c43062d23cb6da","bet_amount":"0.00010000","payout":"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span style=\"color: #03a9f4\">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    3.00\u00d7
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <\/span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ","profit":"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            0.00000000
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <\/span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "},{"game_id":"1055959534","date":"12:59:12","user_id":"251410","user_name":"wbhaao","game":"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span title=\"verify\" style=\"cursor: pointer\" onclick=\"show_bet_info(1055959534)\">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <i class=\"fas fa-lemon\">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <\/i>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Slots
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <\/span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ","nonce":"969","client_seed":"1ada5563141d4855","server_seed":"a4c83534e2d3fb66aad88ec33efccc22e5bcc92d85471faa359f8c5cc51f3205","bet_amount":"0.00010000","payout":"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span style=\"color: #03a9f4\">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    2.00\u00d7
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <\/span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ","profit":"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span style=\"color: #ff5722\">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            -0.00010000
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <\/span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "},{"game_id":"1055959483","date":"12:59:10","user_id":"251410","user_name":"wbhaao","game":"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span title=\"verify\" style=\"cursor: pointer\" onclick=\"show_bet_info(1055959483)\">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <i class=\"fas fa-lemon\">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <\/i>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Slots
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <\/span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ","nonce":"968","client_seed":"1ada5563141d4855","server_seed":"242b01252cb488340ce8d1b0b47e25825a1e52fa25a6536e2c318c49240e97c4","bet_amount":"0.00010000","payout":"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span style=\"color: #03a9f4\">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    4.00\u00d7
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <\/span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ","profit":"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span style=\"color: #38cb74\">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            0.00010000
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <\/span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "},{"game_id":"1055959434","date":"12:59:09","user_id":"251410","user_name":"wbhaao","game":"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span title=\"verify\" style=\"cursor: pointer\" onclick=\"show_bet_info(1055959434)\">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <i class=\"fas fa-lemon\">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <\/i>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Slots
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <\/span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ","nonce":"967","client_seed":"1ada5563141d4855","server_seed":"dcb346fc3f3cf8fe114bbcceefb4ff22ae84df92005b1addb2bf3c392dfcf470","bet_amount":"0.00010000","payout":"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span style=\"color: #03a9f4\">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    0.00\u00d7
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <\/span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ","profit":"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span style=\"color: #ff5722\">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            -0.00030000
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <\/span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "},{"game_id":"1055959382","date":"12:59:08","user_id":"251410","user_name":"wbhaao","game":"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span title=\"verify\" style=\"cursor: pointer\" onclick=\"show_bet_info(1055959382)\">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <i class=\"fas fa-lemon\">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <\/i>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Slots
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <\/span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ","nonce":"966","client_seed":"1ada5563141d4855","server_seed":"265be58cdf13bca7916e310cac3271838f5c56bc90b2cd4efa1e7ba65b2657c6","bet_amount":"0.00010000","payout":"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span style=\"color: #03a9f4\">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    2.00\u00d7
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <\/span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ","profit":"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span style=\"color: #ff5722\">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            -0.00010000<\/span>"}]}
